ASPMVC/Controllers/GunsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ASPMVC.Models;
using ASPMVC.Data;
using Microsoft.AspNetCore.Authorization;

namespace ASPMVC.Controllers
{
    public class GunsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public GunsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Guns
        public async Task<IActionResult> Index(string gunType, string searchString)
        {
            var guns = from g in _context.Gun.Include(c => c.Manufacturer).AsNoTracking()
                select g;

            if (!String.IsNullOrEmpty(searchString))
            {
                guns = guns.Where(s => s.Name.Contains(searchString));
            }

            if (!String.IsNullOrEmpty(gunType))
            {
                guns = guns.Where(x => x.Type == (GunType)int.Parse(gunType));
            }

            var gunTypeVM = new GunTypeViewModel
            {
                Guns = await guns.ToListAsync()
            };

            return View(gunTypeVM);
        }

        // GET: Guns/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var gun = await _context.Gun
                .Include(s => s.Manufacturer)
                .AsNoTracking()
                .SingleOrDefaultAsync(m => m.ID == id);

            if (gun == null)
            {
                return NotFound();
            }

            return View(gun);
        }

        // GET: Guns/Create
        [Authorize(Roles = "Administrator")]
        public IActionResult Create()
        {
            GunManufacturerDropDownList();
            return View();
        }

        // POST: Guns/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Create([Bind("ID,Name,ProductionDate,Type,Caliber,Price,ManufacturerID")] Gun gun)
        {
            if (ModelState.IsValid)
            {
                _context.Add(gun);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            GunManufacturerDropDownList(gun.ManufacturerID);
            return View(gun);
        }

        // GET: Guns/Edit/5
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var gun = await _context.Gun.FindAsync(id);
            if (gun == null)
            {
                return NotFound();
            }
            GunManufacturerDropDownList(gun.ManufacturerID);
            return View(gun);
        }

        // POST: Guns/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Name,ProductionDate,Type,Caliber,Price,ManufacturerID")] Gun gun)
        {
            if (id != gun.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(gun);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!GunExists(gun.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(gun);
        }

        // GET: Guns/Delete/5
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var gun = await _context.Gun
                .FirstOrDefaultAsync(m => m.ID == id);
            if (gun == null)
            {
                return NotFound();
            }

            return View(gun);
        }

        // POST: Guns/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var gun = await _context.Gun.FindAsync(id);
            _context.Gun.Remove(gun);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool GunExists(int id)
        {
            return _context.Gun.Any(e => e.ID == id);
        }

        // Manufacturer Dropdown List
        private void GunManufacturerDropDownList(object selectedManufacturer = null)
        {
            var manufacturersQuery = from m in _context.Manufacturer
                                   orderby m.Name
                                   select m;
            ViewBag.ManufacturerID = new SelectList(manufacturersQuery.AsNoTracking(), "ManufacturerID", "Name", selectedManufacturer);
        }
    }
}

ASPMVC/Controllers/ManufacturersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ASPMVC.Models;
using ASPMVC.Data;
using Microsoft.AspNetCore.Authorization;

namespace ASPMVC.Controllers
{
    public class ManufacturersController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ManufacturersController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Manufacturers
        public async Task<IActionResult> Index()
        {
            return View(await _context.Manufacturer.ToListAsync());
        }

        // GET: Manufacturers/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            ProducedGunsViewModel model = new ProducedGunsViewModel();
            if (id == null)
            {
                return NotFound();
            }

            var manufacturer = await _context.Manufacturer
                .FirstOrDefaultAsync(m => m.ManufacturerID == id);
            if (manufacturer == null)
            {
                return NotFound();
            }

            model.Manufacturer = manufacturer;

            var quey = from gun
                       in (await _context.Gun.ToListAsync())
                       where (gun.ManufacturerID == id)
                       select gun;

            List<Gun> GunList = new List<Gun>();

            foreach (var item in quey)
            {
                GunList.Add(item);
            }
            model.Guns = GunList;
            return View(model);
        }

        // GET: Manufacturers/Create
        [Authorize(Roles = "Administrator")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Manufacturers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Create([Bind("ManufacturerID,Name,Country,Headquarters,FoundDate")] Manufacturer manufacturer)
        {
            if (ModelState.IsValid)
            {
                _context.Add(manufacturer);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(manufacturer);
        }

        // GET: Manufacturers/Edit/5
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var manufacturer = await _context.Manufacturer.FindAsync(id);
            if (manufacturer == null)
            {
                return NotFound();
            }
            return View(manufacturer);
        }

        // POST: Manufacturers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Edit(int id, [Bind("ManufacturerID,Name,Country,Headquarters,FoundDate")] Manufacturer manufacturer)
        {
            if (id != manufacturer.ManufacturerID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(manufacturer);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ManufacturerExists(manufacturer.ManufacturerID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(manufacturer);
        }

        // GET: Manufacturers/Delete/5
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var manufacturer = await _context.Manufacturer
                .FirstOrDefaultAsync(m => m.ManufacturerID == id);
            if (manufacturer == null)
            {
                return NotFound();
            }

            return View(manufacturer);
        }

        // POST: Manufacturers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var manufacturer = await _context.Manufacturer.FindAsync(id);
            _context.Manufacturer.Remove(manufacturer);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ManufacturerExists(int id)
        {
            return _context.Manufacturer.Any(e => e.ManufacturerID == id);
        }
    }
}

ASPMVC/Views/Shared/_GunManufacturerPartial.cshtml
@model ASPMVC.Models.Manufacturer
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

<thead>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Country)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Headquarters)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FoundDate)
        </th>
        <th></th>
    </tr>
</thead>
<tbody>
    <tr>
        <td>
            @Html.DisplayFor(model => model.Name)
        </td>
        <td>
            @Html.DisplayFor(model => model.Country)
        </td>
        <td>
            @Html.DisplayFor(model => model.Headquarters)
        </td>
        <td>
            @Html.DisplayFor(model => model.FoundDate)
        </td>
        @if (SignInManager.IsSignedIn(User) && (this.User.IsInRole("Administrator")))
        {
            <td>
                <a asp-controller="Manufacturers" asp-action="Edit" asp-route-id="@Model.ManufacturerID">Edit</a> |
                <a asp-controller="Manufacturers" asp-action="Delete" asp-route-id="@Model.ManufacturerID">Delete</a>
            </td>
        }
    </tr>
</tbody>

ASPMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Gun Service</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE="/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Gun Service</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div class="sidenav">
        <a asp-area="" asp-controller="Home" asp-action="Index">Home</a>
        <a asp-area="" asp-controller="Guns" asp-action="Index">Guns</a>
        <a asp-area="" asp-controller="Manufacturers" asp-action="Index">Manufacturers</a>
    </div>

    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - Gun Service - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

ASPMVC/Views/Shared/_ProducedGunsPartial.cshtml
@model ASPMVC.Models.Gun
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

<tr>
    <gun-details for-name="Name" for-production="ProductionDate" for-type="Type" for-caliber="Caliber" for-price="Price"></gun-details>
    @if (SignInManager.IsSignedIn(User) && (this.User.IsInRole("Administrator")))
    {
        <td>
            <a asp-controller="Guns" asp-action="Edit" asp-route-id="@Model.ID">Edit</a> |
            <a asp-controller="Guns" asp-action="Delete" asp-route-id="@Model.ID">Delete</a>
        </td>
    }
</tr>